### Get all persons (Exercise 3.1)
GET http://localhost:3001/api/persons

###

### Get info page (Exercise 3.2)
GET http://localhost:3001/info

###

### Get single person (Exercise 3.3)
GET http://localhost:3001/api/persons/1

###

### Get non-existent person (Exercise 3.3)
GET http://localhost:3001/api/persons/999

###

### Delete person (Exercise 3.4)
DELETE http://localhost:3001/api/persons/2

###

### Add new person (Exercise 3.5 & 3.6)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Person",
  "number": "123-456-7890"
}

###

### Add person without name (Exercise 3.6 - should fail)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-456-7890"
}

###

### Add person without number (Exercise 3.6 - should fail)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Person"
}

###

### Add duplicate name (Exercise 3.6 - should fail)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "999-999-9999"
}